const config = {
  baseUrl: "https://done-done-beta.vercel.app",
  appName: "DoneDone",
  appDescription: "A sleek and simple todo list app",
  creator: "Jitendra Nirnejak",
  authorName: "Jitendra Nirnejak",
  authorUrl: "https://nirnejak.com/",
  keywords: [
    "Todo List",
    "TypeScript",
    "Next.js",
    "Drizzle",
    "MySQL",
    "Vitest",
    "TailwindCSS",
    "Framer Motion",
    "Akar Icons",
    "ESLint",
    "Prettier",
    "JavaScript",
  ],
  twitterSite: "@jeetnirnejak",
  twitterCreator: "@jeetnirnejak",
}
export default config
